### ISSUE TITLE
hilfe bitte

### ISSUE THREAD

**Issue by sander030** [BigBen2003/pi-hole-gui-german#1]
ich komm mit dem update bash script nicht zurecht, könntest du mir verraten wie ich dass installieren kann. ich bin ein neuling in dieser branche und weiss nicht weiter....so gerne aber würde ich die oberfläche meines pi holes auf deutsch haben. eine schrit für schritt anleitung wäre super geil! gruß

**Comment by BigBen2003** [comment]
Hallo,
eine Schritt-für-Schritt-Anleitung ist in die Datei _INSTALL.md_ eingestellt worden.

Das **replace-german** Script wurde auch nochmals angepasst, 

Am Besten ist es, wenn mit **git clone** ein Klone eine lokale Kopie angelegt wird.

Künftige Änderungen können dann mit **git pull** übernommen werden.

**Comment by sander030** [comment]
Sehr geil!
hat funktioniert!

vielen Dank!

**Comment by sander030** [comment]
leider kann ich den bereich Einstellungen jetzt nicht mehr öffnen seid dem ich es auf deutsch habe....woran liegt  das?

**Comment by BigBen2003** [comment]
Hallo sander030,,

die Frage ist unvollständig eingetragen worden. Welcher Bereich kann nicht geöffnet werden?
Am besten ein Screenshot mit anhängen.

**Comment by BigBen2003** [comment]
Hallo sander030,

in der Einstellungen-Webseite ist eine Ersetzung falsch durchgeführt worden. Dieser Fehler ist in der letzten Version behoben worden.

Bitte daran denken, dass bei Bedarf auch der Cache gelöscht werden muss, damit die neuen Änderungen  im Browser geladen werden.

**Comment by sander030** [comment]
hi, 

ich habe alles jetzt so durch geführt, die settings lassen sich jetzt auch öffnen, aber nach der ausführung des updates bekomme ich als ersten punkt direkt eine fehlermeldung und die zahlen werden dannach nicht mehr aangzeigt
![Bildschirmfoto zu 2019-10-18 17-36-05](https://user-images.githubusercontent.com/51116095/67108263-6d405380-f1ce-11e9-9683-ec4714f4787c.png)
![Bildschirmfoto zu 2019-10-18 17-35-04](https://user-images.githubusercontent.com/51116095/67108274-70d3da80-f1ce-11e9-947f-f9e347cdbf4a.png)

**Comment by BigBen2003** [comment]
Hallo Sander030,

 

im Script "replace-german" kann eine wichtige neue Datei "germanFiles/Funcs.js" nicht gefunden werden.

 

Die Datei sollte im Repository enthalten sein.

 

Workarround: Bitte kopiere den Pfad "GermanFiles" in den Pfad /var/www/html/admin .

Danach sollte wieder alles angezeigt werden.

 

Gesendet: Freitag, 18. Oktober 2019 um 17:41 Uhr
Von: "sander030" <notifications@github.com>
An: BigBen2003/pi-hole-gui-german <pi-hole-gui-german@noreply.github.com>
Cc: BigBen2003 <dsoetebeer@web.de>, "State change" <state_change@noreply.github.com>
Betreff: Re: [BigBen2003/pi-hole-gui-german] hilfe bitte (#1)


hi,

ich habe alles jetzt so durch geführt, die settings lassen sich jetzt auch öffnen, aber nach der ausführung des updates bekomme ich als ersten punkt direkt eine fehlermeldung und die zahlen werden dannach nicht mehr aangzeigt

**Comment by sander030** [comment]
yes hat geklappt! vielen dank für die meisterleistung

**Comment by BigBen2003** [comment]
Hallo sander030,

 

vielen Dank für die Rückmeldung.

 

Freut mich, dass es alles geklappt hat.

 

Im neuen Replace-German Script wurde der Kopier-Befehl dahingehend angepasst, dass dieser immer die Dateien im Repository findet.

 



Gesendet: Freitag, 18. Oktober 2019 um 18:27 Uhr
Von: "sander030" <notifications@github.com>
An: BigBen2003/pi-hole-gui-german <pi-hole-gui-german@noreply.github.com>
Cc: BigBen2003 <dsoetebeer@web.de>, "State change" <state_change@noreply.github.com>
Betreff: Re: [BigBen2003/pi-hole-gui-german] hilfe bitte (#1)


yes hat geklappt! vielen dank für die meisterleistung

**Comment by sander030** [comment]
hab noch ein problem, die settings werden jetzt nicht gespeichert 
![Bildschirmfoto zu 2019-10-18 19-54-37](https://user-images.githubusercontent.com/51116095/67116697-45a6b680-f1e1-11e9-8c66-4e5cc1433bf9.png)

**Comment by sander030** [comment]
Ist das Problem nun behoben?

**Comment by BigBen2003** [comment]
Das Problem mit der Einstellungsseite ist beseitigt.

**Comment by sander030** [comment]
Leider lassen sich die Einstellungen nicht abspeichern...

**Comment by sander030** [comment]
Alle blocklisten müssen jedesmal neu markiert werden

**Comment by BigBen2003** [comment]
Sorry, das Problem lässt sich nicht so einfach beseitigen. Es ist aber in Arbeit.

**Comment by BigBen2003** [comment]
Die  Webseite "Einstellungen" -> Tab DNS zeigt wieder korrekte Werte an.

Bitte das Script replace-german nochmals ausführen, nachdem das Repository aktualisiert wurde.
